package com.meetly.common;

public enum ErrorCode {
    VALIDATION_FAILED,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    MEETING_NOT_FOUND,
    MEETING_ENDED,
    MEETING_NOT_STARTED,
    NOT_MEETING_HOST,
    NOT_A_MEMBER,
    DISPLAY_NAME_REQUIRED,
    GUEST_MEETING_FORBIDDEN,
    PARTICIPANT_NOT_FOUND,
    MESSAGE_NOT_FOUND,
    INTERNAL_ERROR
}
