apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: livekit
spec:
  type: LoadBalancer
  selector: { app: coturn }
  ports:
    - { name: turns-tcp, port: 443, targetPort: 443, protocol: TCP }
    - { name: turn-udp, port: 3478, targetPort: 3478, protocol: UDP }
    - { name: turn-tcp, port: 3478, targetPort: 3478, protocol: TCP }
